In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [4]:
np.random.seed(25)
DF_obj = DataFrame(np.random.rand(36).reshape(6,6), 
                   index=['row 1', 'row 2','row 3','row 4','row 5','row 6'], 
                   columns=['col 1', 'col 2','col 3','col 4','col 5','col 6'])

In [5]:
DF_obj

          col 1     col 2     col 3     col 4     col 5     col 6
row 1  0.870124  0.582277  0.278839  0.185911  0.411100  0.117376
row 2  0.684969  0.437611  0.556229  0.367080  0.402366  0.113041
row 3  0.447031  0.585445  0.161985  0.520719  0.326051  0.699186
row 4  0.366395  0.836375  0.481343  0.516502  0.383048  0.997541
row 5  0.514244  0.559053  0.034450  0.719930  0.421004  0.436935
row 6  0.281701  0.900274  0.669612  0.456069  0.289804  0.525819

In [21]:
#array size
row = 7
col = 5

#array calc
randome_num = row * col

nDF_obj = DataFrame(np.random.rand(randome_num).reshape(row,col),
                    index=[f"row {n}" for n in range(1, row + 1)],
                    columns=[f"column {n}" for n in range(1, col + 1)] )

In [22]:
nDF_obj

       column 1  column 2  column 3  column 4  column 5
row 1  0.470992  0.819737  0.070855  0.106414  0.507698
row 2  0.431639  0.393481  0.463856  0.488138  0.317365
row 3  0.537020  0.760302  0.866141  0.798727  0.028147
row 4  0.525692  0.670600  0.375215  0.075203  0.669065
row 5  0.590330  0.734630  0.366946  0.007530  0.289300
row 6  0.402361  0.628927  0.450503  0.453651  0.020100
row 7  0.962513  0.686381  0.461716  0.256673  0.421346

In [28]:
nDF_obj.loc[['row 1', 'row 3'],['column 2', 'column 5']]

       column 2  column 5
row 1  0.819737  0.507698
row 3  0.760302  0.028147

In [31]:
nDF_obj[2:4]

       column 1  column 2  column 3  column 4  column 5
row 3  0.537020  0.760302  0.866141  0.798727  0.028147
row 4  0.525692  0.670600  0.375215  0.075203  0.669065